# Generated by Django 3.0.2 on 2020-01-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='u', max_length=30)),
                ('lname', models.CharField(default='u', max_length=30)),
                ('degree', models.CharField(default='u', max_length=30)),
                ('exper', models.IntegerField(default=10)),
                ('hospname', models.CharField(default='u', max_length=30)),
                ('no', models.CharField(default='u', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('pass1', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='u', max_length=30)),
                ('lname', models.CharField(default='u', max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('height', models.IntegerField(default=10)),
                ('weight', models.IntegerField(default=10)),
                ('bgroup', models.CharField(max_length=5)),
                ('Email', models.EmailField(max_length=254)),
                ('qid', models.IntegerField()),
                ('allergy', models.TextField()),
                ('address', models.TextField(default='u')),
                ('no', models.CharField(default='u', max_length=10)),
            ],
        ),
    ]
